//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountVocherMasterTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountVocherMasterTemp()
        {
            this.AccountVocherChildTemps = new HashSet<AccountVocherChildTemp>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int TransectionId { get; set; }
        public string VocherId { get; set; }
        public string VoucherType { get; set; }
        public System.DateTime VocherDate { get; set; }
        public string Remarks { get; set; }
        public bool Posted { get; set; }
        public string PostedFrom { get; set; }
        public string PostedFromType { get; set; }
        public string FYear { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ManualBillNo { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountVocherChildTemp> AccountVocherChildTemps { get; set; }
        public virtual BusinessUnitsInfo BusinessUnitsInfo { get; set; }
    }
}
