//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_VendorQuotationChild
    {
        public int VendorQuotationChildId { get; set; }
        public int VendorQuotationId { get; set; }
        public string ItemCode { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> DestinationFromId { get; set; }
        public Nullable<int> DestinationToId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual AML_City AML_City { get; set; }
        public virtual AML_City AML_City1 { get; set; }
        public virtual AML_FleetService AML_FleetService { get; set; }
        public virtual AML_VendorQuotation AML_VendorQuotation { get; set; }
    }
}
