//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_Dispatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_Dispatch()
        {
            this.AML_DispatchDetail = new HashSet<AML_DispatchDetail>();
        }
    
        public int DispatchId { get; set; }
        public string DispatchNo { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> PickupOrderId { get; set; }
        public string Agent { get; set; }
        public string ProjectName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string RefNo { get; set; }
        public string GatePassNo { get; set; }
        public string DriverName { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte StatusId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
    
        public virtual AML_Customers AML_Customers { get; set; }
        public virtual AML_PickupOrder AML_PickupOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_DispatchDetail> AML_DispatchDetail { get; set; }
    }
}
