//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_WarehouseTransection
    {
        public long WarehouseTransectionId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> ShipmentNoteId { get; set; }
        public Nullable<int> DispatchId { get; set; }
        public string Location { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string ItemId { get; set; }
        public string BatchCode { get; set; }
        public Nullable<System.DateTime> TransctionDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<double> Price { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public string PalletNo { get; set; }
        public string RecordReference { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
