//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_PickupOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_PickupOrder()
        {
            this.AML_Dispatch = new HashSet<AML_Dispatch>();
            this.AML_PickupOrderChild = new HashSet<AML_PickupOrderChild>();
        }
    
        public int PickupOrderId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerOrderNo { get; set; }
        public Nullable<byte> PickupMethod { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public string PCRNo { get; set; }
        public string IRNo { get; set; }
        public string Plant { get; set; }
        public string OriginWarehouse { get; set; }
        public string ContactPerson { get; set; }
        public string Consignee { get; set; }
        public string ConsigneeContact { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public string State { get; set; }
        public string AML_Country { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte StatusId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
    
        public virtual AML_City AML_City { get; set; }
        public virtual AML_Customers AML_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_Dispatch> AML_Dispatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_PickupOrderChild> AML_PickupOrderChild { get; set; }
    }
}
