//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_Region()
        {
            this.AML_City = new HashSet<AML_City>();
            this.AML_Vendor = new HashSet<AML_Vendor>();
        }
    
        public int RegionId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public int ProvinceId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<byte> StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_City> AML_City { get; set; }
        public virtual AML_Company AML_Company { get; set; }
        public virtual AML_Province AML_Province { get; set; }
        public virtual AML_TenderDetail AML_TenderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_Vendor> AML_Vendor { get; set; }
    }
}
