//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_GodownRack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_GodownRack()
        {
            this.AML_GodownShelf = new HashSet<AML_GodownShelf>();
        }
    
        public int GodownRackId { get; set; }
        public Nullable<int> GodwonId { get; set; }
        public Nullable<int> GodownRowId { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte StatusId { get; set; }
    
        public virtual AML_GodownRow AML_GodownRow { get; set; }
        public virtual AML_Godwom AML_Godwom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_GodownShelf> AML_GodownShelf { get; set; }
    }
}
