//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_TenderChild
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int TenderId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> FleetServiceId { get; set; }
        public Nullable<int> TenderDetailId { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public Nullable<byte> IsJobExecuted { get; set; }
    
        public virtual AML_FleetService AML_FleetService { get; set; }
        public virtual AML_Tender AML_Tender { get; set; }
        public virtual AML_TenderDetail AML_TenderDetail { get; set; }
        public virtual AML_Vehicles AML_Vehicles { get; set; }
    }
}
