//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_Tender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_Tender()
        {
            this.AML_ContractCancelation = new HashSet<AML_ContractCancelation>();
            this.AML_Job = new HashSet<AML_Job>();
            this.AML_TenderChild = new HashSet<AML_TenderChild>();
            this.AML_TenderDetail = new HashSet<AML_TenderDetail>();
            this.AML_VendorQuotation = new HashSet<AML_VendorQuotation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string TenderReference { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public string TenderSource { get; set; }
        public string TenderTerm { get; set; }
        public string TenderNo { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<byte> ProceedStatus { get; set; }
        public Nullable<System.DateTime> TenderExpiryDate { get; set; }
        public string Gst { get; set; }
        public string FurthurTax { get; set; }
        public string AdditionalTax { get; set; }
        public string WithHoldingTax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_ContractCancelation> AML_ContractCancelation { get; set; }
        public virtual AML_Customers AML_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_Job> AML_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_TenderChild> AML_TenderChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_TenderDetail> AML_TenderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_VendorQuotation> AML_VendorQuotation { get; set; }
    }
}
