//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_Godwom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_Godwom()
        {
            this.AML_GodownRack = new HashSet<AML_GodownRack>();
            this.AML_GodownRow = new HashSet<AML_GodownRow>();
            this.AML_GodownShelf = new HashSet<AML_GodownShelf>();
        }
    
        public int GodwomId { get; set; }
        public string Name { get; set; }
        public string GodwomNo { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<int> GodwomTypeId { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_GodownRack> AML_GodownRack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_GodownRow> AML_GodownRow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_GodownShelf> AML_GodownShelf { get; set; }
        public virtual AML_GodwomType AML_GodwomType { get; set; }
        public virtual AML_Warehouse AML_Warehouse { get; set; }
    }
}
