//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_PickupOrderChild
    {
        public int PickupOrderChildId { get; set; }
        public Nullable<int> PickupOrderId { get; set; }
        public string RelOrd { get; set; }
        public string ItemId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        public virtual AML_ItemInformation AML_ItemInformation { get; set; }
        public virtual AML_PickupOrder AML_PickupOrder { get; set; }
        public virtual AML_Units AML_Units { get; set; }
    }
}
