//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_ItemInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_ItemInformation()
        {
            this.AML_DispatchDetail = new HashSet<AML_DispatchDetail>();
            this.AML_PickupOrderChild = new HashSet<AML_PickupOrderChild>();
            this.AML_ShipmentNoteChild = new HashSet<AML_ShipmentNoteChild>();
        }
    
        public string ItemInformationId { get; set; }
        public string ItemId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public int Length { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<int> MinStockLevel { get; set; }
        public Nullable<int> MaxStockLevel { get; set; }
        public Nullable<int> QuantityInPacking { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public byte StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_DispatchDetail> AML_DispatchDetail { get; set; }
        public virtual AML_Item AML_Item { get; set; }
        public virtual AML_Units AML_Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_PickupOrderChild> AML_PickupOrderChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_ShipmentNoteChild> AML_ShipmentNoteChild { get; set; }
    }
}
