//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_ContractCancelation
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int CancelationBy { get; set; }
        public System.DateTime CancelationDate { get; set; }
        public string Reasion { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual AML_Tender AML_Tender { get; set; }
    }
}
