//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_FinancialYearDefination
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string FYearTitle { get; set; }
        public System.DateTime FYearStartDate { get; set; }
        public System.DateTime FYearEndDate { get; set; }
        public Nullable<bool> FYearActive { get; set; }
        public Nullable<bool> FYearLocked { get; set; }
        public Nullable<byte> StatusId { get; set; }
    
        public virtual AML_Company AML_Company { get; set; }
    }
}
