//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_ShipmentNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AML_ShipmentNote()
        {
            this.AML_ShipmentNoteChild = new HashSet<AML_ShipmentNoteChild>();
        }
    
        public int ShipmentNoteId { get; set; }
        public string ShipmentNoteNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CargoStatus { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string Remarks { get; set; }
        public string ASNNo { get; set; }
        public string DeliveryNo { get; set; }
        public Nullable<System.DateTime> ASNDate { get; set; }
        public string DriverName { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public byte StatusId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual AML_Warehouse AML_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AML_ShipmentNoteChild> AML_ShipmentNoteChild { get; set; }
    }
}
