//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceAndOverTimeLock
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string EmployeeId { get; set; }
        public string WorkingHour { get; set; }
        public double AllowedWorkingHour { get; set; }
        public System.DateTime Date { get; set; }
        public string Attendance { get; set; }
        public double TotalHours { get; set; }
        public string TotalTimeDiffInHour { get; set; }
        public double FinalOverTime { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
