//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDayMarkType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendanceDayMarkType()
        {
            this.AttendanceDayMarks = new HashSet<AttendanceDayMark>();
            this.EmployeeLeavesAlloweds = new HashSet<EmployeeLeavesAllowed>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int AttendanceDayMarkTypeid { get; set; }
        public string AttendanceTypeName { get; set; }
        public string AttandanceTypeDescription { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceDayMark> AttendanceDayMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeavesAllowed> EmployeeLeavesAlloweds { get; set; }
    }
}
