//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string EmployeeId { get; set; }
        public int EmployeeUid { get; set; }
        public int ShiftId { get; set; }
        public int ShiftUid { get; set; }
        public int AttendanceId { get; set; }
        public System.DateTime AttendanceTime { get; set; }
        public string Action { get; set; }
        public Nullable<bool> MarkBy { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual BusinessUnitsInfo BusinessUnitsInfo { get; set; }
        public virtual CompanyInfo CompanyInfo { get; set; }
        public virtual ShiftInfo ShiftInfo { get; set; }
    }
}
