//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccountDetail()
        {
            this.ChequeBookRecords = new HashSet<ChequeBookRecord>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int BankAccountId { get; set; }
        public int BankAccountDetailId { get; set; }
        public string ChartAccount { get; set; }
        public string ChequeBookNo { get; set; }
        public System.DateTime ChequeIssueDate { get; set; }
        public string ChequeStartNo { get; set; }
        public string ChequeEndNo { get; set; }
        public double ChequeBookLimit { get; set; }
        public bool ChequeBookStatus { get; set; }
        public bool IsLockedChequeBook { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeBookRecord> ChequeBookRecords { get; set; }
    }
}
