//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfEntryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillOfEntryMaster()
        {
            this.BillOfEntryChilds = new HashSet<BillOfEntryChild>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string BatchId { get; set; }
        public string InvoiceId { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Method { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModefiedDate { get; set; }
        public string LastModefiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfEntryChild> BillOfEntryChilds { get; set; }
    }
}
