//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockWarehouse
    {
        public string BlockSerial { get; set; }
        public string FYearTitle { get; set; }
        public int TransactionId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string BlockId { get; set; }
        public bool Status { get; set; }
        public string Refference { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
