//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Block()
        {
            this.BlockProductionDetails = new HashSet<BlockProductionDetail>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string BlockId { get; set; }
        public string BlockName { get; set; }
        public string BlockNarration { get; set; }
        public Nullable<double> BlockHeight { get; set; }
        public Nullable<double> BlockLength { get; set; }
        public Nullable<double> BlockWeight { get; set; }
        public Nullable<double> BlockWidth { get; set; }
        public Nullable<double> BlockDensity { get; set; }
        public string BlockColor { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockProductionDetail> BlockProductionDetails { get; set; }
    }
}
