//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockProductionDetail
    {
        public string BlockProductionId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string BlockId { get; set; }
        public int ProduceQuantity { get; set; }
        public System.DateTime BlockProductionDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual BlockProduction BlockProduction { get; set; }
    }
}
