//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockCuttingDetail
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string CuttingId { get; set; }
        public System.DateTime CuttingDate { get; set; }
        public string BlockSerial { get; set; }
        public string ItemId { get; set; }
        public int Quantity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual BlockCutting BlockCutting { get; set; }
    }
}
