//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequePaidSummary
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string ChartAccount { get; set; }
        public int Id { get; set; }
        public System.DateTime ChequeIssueDate { get; set; }
        public string IssuedFrom { get; set; }
        public string IssuedTo { get; set; }
        public string ChequeBookNo { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeNaration { get; set; }
        public System.DateTime ClearenceDate { get; set; }
        public double ChequeAmount { get; set; }
        public bool ChequePosted { get; set; }
        public bool ChequeCanceled { get; set; }
        public string VocherId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] Image { get; set; }
    }
}
