//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CompanyId { get; set; }
        public string Region { get; set; }
        public string Zone { get; set; }
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Type { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string FaxNo { get; set; }
        public string AccountNo { get; set; }
        public string NTN { get; set; }
        public string STRN { get; set; }
        public string CNIC { get; set; }
        public string AccountCode { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string Remarks { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public string Item { get; set; }
        public string Bank { get; set; }
        public string SwiftCode { get; set; }
        public string NotifyParty { get; set; }
        public string NotifyAddress { get; set; }
        public string DestinByAir { get; set; }
        public string CountryByAir { get; set; }
        public string DestinBySea { get; set; }
        public string CountryBySea { get; set; }
        public string FOB_CNF_CIF { get; set; }
        public string NotifySea { get; set; }
        public string NotifySeaAddress { get; set; }
        public string WebSite { get; set; }
        public string Designation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
