//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCareFeedBack
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int CustomerId { get; set; }
        public string OrderId { get; set; }
        public string DeliveryId { get; set; }
        public string CustomerCareId { get; set; }
        public int feedBackId { get; set; }
        public string FeedBackDetail { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual CustomerCare CustomerCare { get; set; }
    }
}
