//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Tenders = new HashSet<Tender>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CustomerBusinessLineId { get; set; }
        public double Discount { get; set; }
        public string Type { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string FaxNo { get; set; }
        public string AccountNo { get; set; }
        public string NTN { get; set; }
        public string STRN { get; set; }
        public string CNIC { get; set; }
        public string AccountCode { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string Remarks { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual CustomerBusinessLine CustomerBusinessLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tender> Tenders { get; set; }
    }
}
