//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerCare()
        {
            this.CustomerCareDetails = new HashSet<CustomerCareDetail>();
            this.CustomerCareFeedBacks = new HashSet<CustomerCareFeedBack>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int CustomerId { get; set; }
        public string OrderId { get; set; }
        public string DeliveryId { get; set; }
        public string CustomerCareId { get; set; }
        public System.DateTime Date { get; set; }
        public string ComplaintName { get; set; }
        public string ContactNo { get; set; }
        public string ComplainDetail { get; set; }
        public bool Status { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCareDetail> CustomerCareDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCareFeedBack> CustomerCareFeedBacks { get; set; }
    }
}
