//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchPlanDetail
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string DispatchPlanId { get; set; }
        public int DispatchPlanDetailId { get; set; }
        public string ItemId { get; set; }
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public int CustomerId { get; set; }
        public double ApprovedQuantity { get; set; }
        public double DelievredQuantity { get; set; }
        public double NextSupply { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual DispatchPlan DispatchPlan { get; set; }
        public virtual Order Order { get; set; }
    }
}
