//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchPlanSchedule
    {
        public int BusinessUnitId { get; set; }
        public int OrderId { get; set; }
        public string NextSupply { get; set; }
        public string Status { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
