//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public System.Guid DocumentId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentGroup { get; set; }
        public string DocumentPath { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
