//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTypeOverTime
    {
        public int CompanyId { get; set; }
        public int EmployeeTypeId { get; set; }
        public bool IsDynamic { get; set; }
        public double Value { get; set; }
        public double WorkingHours { get; set; }
        public string DescFormula { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
