//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string login_id { get; set; }
        public int CompanyId { get; set; }
        public int dept_id { get; set; }
        public int design_id { get; set; }
        public string emp_id { get; set; }
        public string name { get; set; }
        public byte[] image { get; set; }
        public string person_email { get; set; }
        public string work_email { get; set; }
        public string country { get; set; }
        public string CNIC { get; set; }
        public string passport_no { get; set; }
        public string account_no { get; set; }
        public string adress { get; set; }
        public string gender { get; set; }
        public string marrital_status { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string education { get; set; }
        public bool employee_status { get; set; }
        public string experience { get; set; }
        public Nullable<double> salary { get; set; }
        public string religion { get; set; }
        public string city { get; set; }
        public string nationality { get; set; }
        public Nullable<System.DateTime> joining_date { get; set; }
        public string employee_type { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public string Phone { get; set; }
    }
}
