//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeavesAllowed
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int EmployeeTypeId { get; set; }
        public int EmployeeAttendanceTypeId { get; set; }
        public int AttendanceDayMarkTypeid { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public Nullable<int> AnnualLeaveDays { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual AttendanceDayMarkType AttendanceDayMarkType { get; set; }
        public virtual EmployeeAttendanceType EmployeeAttendanceType { get; set; }
    }
}
