//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendanceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeAttendanceType()
        {
            this.EmployeeLeavesAlloweds = new HashSet<EmployeeLeavesAllowed>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int EmployeeTypeId { get; set; }
        public int EmployeeAttendanceTypeId { get; set; }
        public bool OverTimeAllowed { get; set; }
        public bool SundayOffAllowed { get; set; }
        public bool LeavesAllowed { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeavesAllowed> EmployeeLeavesAlloweds { get; set; }
    }
}
