//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistory
    {
        public int UniqueId { get; set; }
        public string EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public int EmployeeTypeId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<double> OtherDeduction { get; set; }
        public Nullable<double> SpecialAllowance { get; set; }
        public Nullable<double> PetrolAllowance { get; set; }
        public Nullable<double> MobileAllowance { get; set; }
        public Nullable<double> FoodAllowance { get; set; }
        public Nullable<double> IncomeText { get; set; }
        public Nullable<double> LoneDeduction { get; set; }
        public Nullable<double> EobiDeduction { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual EmployeeInfo EmployeeInfo { get; set; }
    }
}
