//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public Nullable<System.Guid> FileGuId { get; set; }
        public string FileName { get; set; }
        public string FileUploadedName { get; set; }
        public Nullable<int> FileJobId { get; set; }
        public Nullable<int> FileCustomerId { get; set; }
        public Nullable<int> FileContractId { get; set; }
        public Nullable<System.DateTime> FileCreateDate { get; set; }
    }
}
