//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialYearDefination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialYearDefination()
        {
            this.FinancialYearDetails = new HashSet<FinancialYearDetail>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string FYearTitle { get; set; }
        public System.DateTime FYearStartDate { get; set; }
        public System.DateTime FYearEndDate { get; set; }
        public Nullable<bool> FYearActive { get; set; }
        public Nullable<bool> FYearLocked { get; set; }
    
        public virtual BusinessUnitsInfo BusinessUnitsInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialYearDetail> FinancialYearDetails { get; set; }
    }
}
