//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialYearDetail
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string FYearTitle { get; set; }
        public System.Guid Login { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> FYearStartDate { get; set; }
        public Nullable<System.DateTime> FYearEndDate { get; set; }
        public Nullable<bool> FYearAllowed { get; set; }
        public Nullable<bool> FYearActive { get; set; }
        public Nullable<bool> FYearLocked { get; set; }
    
        public virtual FinancialYearDefination FinancialYearDefination { get; set; }
        public virtual Registration_User Registration_User { get; set; }
    }
}
