//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_WareHouseTransferSaleAudit
    {
        public int AuditId { get; set; }
        public Nullable<int> FromCompanyId { get; set; }
        public Nullable<int> FromBusinessUnitId { get; set; }
        public Nullable<int> FromWareHouseId { get; set; }
        public Nullable<double> TransferedQuantity { get; set; }
        public Nullable<int> ToCompanyId { get; set; }
        public Nullable<int> ToWareHouseId { get; set; }
        public string Remarks { get; set; }
    }
}
