//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_LetterOfCreditTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_LetterOfCreditTypes()
        {
            this.inv_LetterOfCredit = new HashSet<inv_LetterOfCredit>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int LCTypeId { get; set; }
        public string LCTypeName { get; set; }
        public string LCTypeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_LetterOfCredit> inv_LetterOfCredit { get; set; }
    }
}
