//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_ItemDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_ItemDetail()
        {
            this.inv_GatePassDetailItems = new HashSet<inv_GatePassDetailItems>();
            this.inv_purchaseDemandNoteDetail = new HashSet<inv_purchaseDemandNoteDetail>();
            this.inv_PurchaseOrderDetail = new HashSet<inv_PurchaseOrderDetail>();
            this.inv_purchaseRecognizationDetail = new HashSet<inv_purchaseRecognizationDetail>();
            this.inv_TenderDetail = new HashSet<inv_TenderDetail>();
            this.inv_VendorQuotationDetail = new HashSet<inv_VendorQuotationDetail>();
            this.inv_Warehouse = new HashSet<inv_Warehouse>();
            this.inv_WareHouseLog = new HashSet<inv_WareHouseLog>();
        }
    
        public int CompanyId { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public double ItemPrice { get; set; }
        public int UnitMeasureId { get; set; }
        public double MinStockLevel { get; set; }
        public double MaxStockLevel { get; set; }
        public string ItemSize { get; set; }
        public Nullable<double> ItemWeight { get; set; }
        public Nullable<double> ItemHeight { get; set; }
        public Nullable<double> ItemWidth { get; set; }
        public string AccountCode { get; set; }
        public bool IsRawMaterial { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public int TransectionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_GatePassDetailItems> inv_GatePassDetailItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_purchaseDemandNoteDetail> inv_purchaseDemandNoteDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_PurchaseOrderDetail> inv_PurchaseOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_purchaseRecognizationDetail> inv_purchaseRecognizationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_TenderDetail> inv_TenderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_VendorQuotationDetail> inv_VendorQuotationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_Warehouse> inv_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_WareHouseLog> inv_WareHouseLog { get; set; }
    }
}
