//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PostedVoucher
    {
        public int CompanyId { get; set; }
        public long TransectionId { get; set; }
        public string ItemId { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
