//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_PurchaseOrder()
        {
            this.inv_PurchaseOrderDetail = new HashSet<inv_PurchaseOrderDetail>();
        }
    
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string PurchaseOrderId { get; set; }
        public string RecogzitionId { get; set; }
        public string TenderId { get; set; }
        public string QuotationId { get; set; }
        public int VendorId { get; set; }
        public string PurchaseOrderStatus { get; set; }
        public System.DateTime PurchaseOrderDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> ExtraGST { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public string DeliveryCompletion { get; set; }
        public string PaymentType { get; set; }
        public string Sample { get; set; }
        public string BillNo { get; set; }
    
        public virtual inv_Vendors inv_Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_PurchaseOrderDetail> inv_PurchaseOrderDetail { get; set; }
    }
}
