//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_BinCartDefination
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int WarehouseId { get; set; }
        public string BinCartId { get; set; }
        public string BinCartName { get; set; }
        public string BinCartDescription { get; set; }
        public string BinCartSize { get; set; }
        public Nullable<double> BinCartHeight { get; set; }
        public Nullable<double> BinCartWidth { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
