//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_VendorQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_VendorQuotation()
        {
            this.inv_VendorQuotationDetail = new HashSet<inv_VendorQuotationDetail>();
        }
    
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string QuotationId { get; set; }
        public string TenderId { get; set; }
        public string RecogzitionId { get; set; }
        public int VendorId { get; set; }
        public string CashOrCredit { get; set; }
        public System.DateTime QuotationDate { get; set; }
        public Nullable<System.DateTime> QuotationApproveDate { get; set; }
        public string Remarks { get; set; }
        public string QuotationStatus { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual inv_Vendors inv_Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_VendorQuotationDetail> inv_VendorQuotationDetail { get; set; }
    }
}
