//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_TestViewForItemVarient
    {
        public string ItemName { get; set; }
        public double ItemPrice { get; set; }
        public double MaxStockLevel { get; set; }
        public string Size { get; set; }
        public string Density { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
    }
}
