//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_PurchaseDemandNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_PurchaseDemandNote()
        {
            this.inv_purchaseDemandNoteDetail = new HashSet<inv_purchaseDemandNoteDetail>();
        }
    
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string PdnId { get; set; }
        public int DepartmentId { get; set; }
        public string EmpolyeeId { get; set; }
        public System.DateTime ProjectionDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public int Priority { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string PurchaseRecogzitionStatus { get; set; }
        public System.DateTime DemandNoteDate { get; set; }
        public string Reference { get; set; }
        public string PerformaInvoiceId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_purchaseDemandNoteDetail> inv_purchaseDemandNoteDetail { get; set; }
    }
}
