//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_LetterOfCredit
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string LCNo { get; set; }
        public string LCId { get; set; }
        public int LCTypeId { get; set; }
        public string AdviseCreditBy { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int VenderId { get; set; }
        public double AmountInFigures { get; set; }
        public string AmountInWords { get; set; }
        public string BankName { get; set; }
        public string AccountTitle { get; set; }
        public string AccountName { get; set; }
        public bool PartialShipment { get; set; }
        public bool Transshipment { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual inv_LetterOfCreditTypes inv_LetterOfCreditTypes { get; set; }
    }
}
