//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_WareHouseLog
    {
        public int LogId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string ItemId { get; set; }
        public int WarehouseIdOld { get; set; }
        public string BinCartIdOld { get; set; }
        public int WarehouseIdNew { get; set; }
        public string BinCartIdNew { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Reason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual inv_ItemDetail inv_ItemDetail { get; set; }
    }
}
