//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_StockLess
    {
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string GrnId { get; set; }
        public string ItemId { get; set; }
        public int StockLessId { get; set; }
        public Nullable<decimal> StockLess { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime StockLessDate { get; set; }
    }
}
