//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvLetterOfCreditDocumentsUpload
    {
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string LatterOfCreditId { get; set; }
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
    }
}
