//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvLetterOfCreditDetail
    {
        public int CompnayId { get; set; }
        public int BusinessUnitId { get; set; }
        public int LcExpansesId { get; set; }
        public int LetterOfCreditDetailId { get; set; }
        public string ExpenseId { get; set; }
        public int CurrencyId { get; set; }
        public string LatterOfCreditId { get; set; }
        public string ChartAccount { get; set; }
        public double Amount { get; set; }
        public double ConversionRate { get; set; }
        public double ConvertedRate { get; set; }
        public string LastModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual inv_CurrencyDefination inv_CurrencyDefination { get; set; }
        public virtual InvExpenseDefination InvExpenseDefination { get; set; }
        public virtual InvLetterOfCreditExpsInfo InvLetterOfCreditExpsInfo { get; set; }
    }
}
