//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvLatterOfCredit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvLatterOfCredit()
        {
            this.InvLetterOfCreditDocuments = new HashSet<InvLetterOfCreditDocument>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string LatterOfCreditId { get; set; }
        public int CurrencyId { get; set; }
        public int LCTypeId { get; set; }
        public string ChartAccount { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string LetterOfCreditNo { get; set; }
        public string Beneficiary { get; set; }
        public double AmountInFigures { get; set; }
        public string AmountInWords { get; set; }
        public string BankName { get; set; }
        public string AccountTitle { get; set; }
        public string AccountName { get; set; }
        public string UplodedFilePath { get; set; }
        public string Terms { get; set; }
        public string CreditAvailableWith { get; set; }
        public string Transhipments { get; set; }
        public string PartialShipments { get; set; }
        public string AdviseCreditBy { get; set; }
        public string TransportationBy { get; set; }
        public string PaymentMod { get; set; }
        public bool Locked { get; set; }
        public string VocherId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string DescriptionOfGoods { get; set; }
        public string NoPackages { get; set; }
        public string ImporterName { get; set; }
        public string ContractWeight { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
    
        public virtual BusinessUnitsInfo BusinessUnitsInfo { get; set; }
        public virtual inv_CurrencyDefination inv_CurrencyDefination { get; set; }
        public virtual LetterOfCreditType LetterOfCreditType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvLetterOfCreditDocument> InvLetterOfCreditDocuments { get; set; }
    }
}
