//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCostingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemCostingDetail()
        {
            this.ItemCostingItemDetails = new HashSet<ItemCostingItemDetail>();
        }
    
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int CustomerId { get; set; }
        public int InquiryId { get; set; }
        public string SalesItemId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int CostingId { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
        public Nullable<bool> Status { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public decimal PerUnitAmount { get; set; }
    
        public virtual ItemCosting ItemCosting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCostingItemDetail> ItemCostingItemDetails { get; set; }
    }
}
