//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public int CompanyId { get; set; }
        public string ItemId { get; set; }
        public string ImagePath { get; set; }
        public string Name { get; set; }
        public int Id { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
