//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class JobQuotationApproval
    {
        public int JobQuotationApprovalId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string JobNo { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        [NotMapped]
        public bool IsJobExecuted { get; set; }
    }
}
