//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterOfCreditType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LetterOfCreditType()
        {
            this.InvLatterOfCredits = new HashSet<InvLatterOfCredit>();
        }
    
        public int CompanyId { get; set; }
        public int LCTypeId { get; set; }
        public string LCTypeName { get; set; }
        public string LCTypeDescription { get; set; }
    
        public virtual CompanyInfo CompanyInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvLatterOfCredit> InvLatterOfCredits { get; set; }
    }
}
