//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanInfo()
        {
            this.MonthlyInstallments = new HashSet<MonthlyInstallment>();
            this.SkipMonthlyInstallments = new HashSet<SkipMonthlyInstallment>();
        }
    
        public int LoanId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string EmployeeId { get; set; }
        public double AmountRequested { get; set; }
        public string ApprovedBy { get; set; }
        public bool LoanStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyInstallment> MonthlyInstallments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkipMonthlyInstallment> SkipMonthlyInstallments { get; set; }
    }
}
