//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manuf_StepStatus
    {
        public int CompanyId { get; set; }
        public string BatchId { get; set; }
        public string ItemId { get; set; }
        public string ProcedureId { get; set; }
        public string StepId { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Createdby { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedby { get; set; }
        public int Id { get; set; }
    }
}
