//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manuf_ItemWiseDepartments
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string ItemId { get; set; }
        public int DepartmentId { get; set; }
        public string PerformInvoiceId { get; set; }
        public Nullable<int> IndexNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Createdby { get; set; }
        public string LastModifiedby { get; set; }
    }
}
