//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleForm
    {
        public int id { get; set; }
        public string formName { get; set; }
        public string formAlias { get; set; }
        public Nullable<int> moduleId { get; set; }
        public Nullable<int> moduleCategoryId { get; set; }
        public Nullable<bool> Navigation { get; set; }
        public Nullable<double> OrderBy { get; set; }
        public string Project { get; set; }
        public string IconClass { get; set; }
    }
}
