//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleForm()
        {
            this.PrivilegesToRoles = new HashSet<PrivilegesToRole>();
        }
    
        public int id { get; set; }
        public string formName { get; set; }
        public string formAlias { get; set; }
        public Nullable<int> moduleId { get; set; }
        public Nullable<int> moduleCategoryId { get; set; }
        public Nullable<bool> Navigation { get; set; }
        public Nullable<double> OrderBy { get; set; }
        public string Project { get; set; }
    
        public virtual ModuleCategory ModuleCategory { get; set; }
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivilegesToRole> PrivilegesToRoles { get; set; }
    }
}
