//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleCategory
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> moduleId { get; set; }
        public string CssClass { get; set; }
        public Nullable<double> OrderBy { get; set; }
        public string Project { get; set; }
    }
}
