//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDeliveryDetail
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string OrderType { get; set; }
        public string OrderId { get; set; }
        public string DeliveryId { get; set; }
        public int ItemDeliveryNo { get; set; }
        public string ItemId { get; set; }
        public double DeliveredQuantity { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual OrderDelivery OrderDelivery { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
