//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformaInvoiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerformaInvoiceMaster()
        {
            this.PerformaInvoiceChilds = new HashSet<PerformaInvoiceChild>();
        }
    
        public int CompanyId { get; set; }
        public string CustomerId { get; set; }
        public string PerformaInvoiceId { get; set; }
        public int BusinessUnitId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Createdby { get; set; }
        public string LastModifiedby { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int InquiryId { get; set; }
        public string InvoiceOf { get; set; }
        public string OrderNr { get; set; }
        public string CountryOfOrigin { get; set; }
        public string ShipmentFrom { get; set; }
        public string ShipmentTo { get; set; }
        public string Terms { get; set; }
        public string Transhipment { get; set; }
        public string PartialShipment { get; set; }
        public string AdviseCreditBy { get; set; }
        public string TransportationBy { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformaInvoiceChild> PerformaInvoiceChilds { get; set; }
    }
}
