//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivilegesToRole
    {
        public int roleId { get; set; }
        public int moduleFormId { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.Guid> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.Guid> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ModuleForm ModuleForm { get; set; }
        public virtual Role Role { get; set; }
    }
}
