//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration_User()
        {
            this.FinancialYearDetails = new HashSet<FinancialYearDetail>();
            this.Registration_BusinessUnitLevel = new HashSet<Registration_BusinessUnitLevel>();
            this.Registration_CompanyLevel = new HashSet<Registration_CompanyLevel>();
        }
    
        public System.Guid Login { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Emp_CompanyId { get; set; }
        public string Emp_Id { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> Emp_BusinessUnitId { get; set; }
    
        public virtual EmployeeInfo EmployeeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialYearDetail> FinancialYearDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration_BusinessUnitLevel> Registration_BusinessUnitLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration_CompanyLevel> Registration_CompanyLevel { get; set; }
        public virtual RolesToUser RolesToUser { get; set; }
    }
}
