//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_BusinessUnitLevel
    {
        public System.Guid Login { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public bool Status { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.Guid> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Registration_CompanyLevel Registration_CompanyLevel { get; set; }
        public virtual Registration_User Registration_User { get; set; }
    }
}
