//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoice
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public string DeliveryId { get; set; }
        public string SaleInvoiceId { get; set; }
        public System.DateTime SaleInvoiceDate { get; set; }
        public string ManualBillNo { get; set; }
        public double FreightExpense { get; set; }
        public double LoadingUnLoadingExpense { get; set; }
        public double PackingExpense { get; set; }
        public double TollExpense { get; set; }
        public double SlittingCharges { get; set; }
        public double CuttingCharges { get; set; }
        public double LabourCharges { get; set; }
        public double BendingChanelling { get; set; }
        public double OtherExpense { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<long> SalesTaxId { get; set; }
        public string FYear { get; set; }
        public Nullable<int> Sale_Invoice_Discount { get; set; }
    }
}
