//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiftInfo()
        {
            this.Attendances = new HashSet<Attendance>();
            this.ShiftHistories = new HashSet<ShiftHistory>();
        }
    
        public int ShiftId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string ShiftName { get; set; }
        public string ShiftCode { get; set; }
        public System.DateTime PunchStartTime { get; set; }
        public bool Status { get; set; }
        public System.DateTime ShiftBeginTime { get; set; }
        public System.DateTime ShiftEndTime { get; set; }
        public double ShiftDurationHours { get; set; }
        public System.DateTime BreakBeginTime { get; set; }
        public System.DateTime BreakEnd { get; set; }
        public double BreakDuration { get; set; }
        public string Remarks { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual BusinessUnitsInfo BusinessUnitsInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftHistory> ShiftHistories { get; set; }
    }
}
