//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Orders
    {
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public string ItemId { get; set; }
        public Nullable<double> appQuantity { get; set; }
    }
}
