//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferStockInventoryToSale
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int TransferId { get; set; }
        public int SaleWarehouseId { get; set; }
        public string SaleWarehouseName { get; set; }
        public int InventoryWarehouseId { get; set; }
        public string InventoryWarehouseName { get; set; }
        public string InventoryBinCardId { get; set; }
        public string InventoryBinCardName { get; set; }
        public string SaleItemId { get; set; }
        public string SaleItemName { get; set; }
        public string InventoryItemId { get; set; }
        public string InventoryItemName { get; set; }
        public double MoveStock { get; set; }
        public System.DateTime TransferDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
