//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferItemsInventoryToSale
    {
        public int AuditId { get; set; }
        public Nullable<int> FromCompanyId { get; set; }
        public string FromCompanyName { get; set; }
        public Nullable<int> FromBusinessUnitId { get; set; }
        public string FromBusinessUnit { get; set; }
        public Nullable<int> FromWareHouseId { get; set; }
        public string FromWarehouseName { get; set; }
        public Nullable<double> TransferedQuantity { get; set; }
        public Nullable<int> ToCompanyId { get; set; }
        public string ToCompanyName { get; set; }
        public Nullable<int> ToWareHouseId { get; set; }
        public string ToWarehouseName { get; set; }
        public string Remarks { get; set; }
        public string FromInventoryItem { get; set; }
        public string ToSaleItem { get; set; }
        public Nullable<int> LogId { get; set; }
        public System.DateTime InventoryWarehouseDate { get; set; }
        public System.DateTime SaleWarehouseDate { get; set; }
        public string SaleCategory { get; set; }
        public string SaleSubCategory { get; set; }
        public string InventoryCategory { get; set; }
        public string InventorySubCategory { get; set; }
        public string InventoryBrand { get; set; }
    }
}
