//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorInvoiceChild
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string VendorId { get; set; }
        public string DocumentRef { get; set; }
        public decimal PaidAmount { get; set; }
        public string Remarks { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string SecondChartAccount { get; set; }
        public string SecondChartAccountTitle { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public int TransctionId { get; set; }
        public string VendorName { get; set; }
        public int ChildId { get; set; }
    
        public virtual VendorInvoiceMasterDetail VendorInvoiceMasterDetail { get; set; }
    }
}
