//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDailySale
    {
        public string Name { get; set; }
        public string ItemName { get; set; }
        public string Date { get; set; }
        public Nullable<double> DeliveredQuantity { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
    }
}
