//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DashBoardTodayEmpAttendance
    {
        public string EmployeeName { get; set; }
        public string DepartmentName { get; set; }
        public string EmployeeTypeName { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string EmployeeId { get; set; }
        public string AttendanceTypeName { get; set; }
    }
}
