//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ReceipewithPrice
    {
        public string InvItemId { get; set; }
        public int WarehoueId { get; set; }
        public string RecipeId { get; set; }
        public decimal Quantity { get; set; }
        public string BatchId { get; set; }
        public string SalesItemId { get; set; }
        public int CompanyId { get; set; }
        public decimal batchQuantity { get; set; }
    }
}
