//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Inv_GetSepratedColumnForItemDetialsOfC_S_B_Item
    {
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Brand { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> ItemHeight { get; set; }
        public Nullable<double> ItemWidth { get; set; }
        public string ItemSize { get; set; }
        public Nullable<double> ItemWeight { get; set; }
        public int UnitMeasureId { get; set; }
        public double ItemPrice { get; set; }
        public string AccountCode { get; set; }
        public double MaxStockLevel { get; set; }
        public double MinStockLevel { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public int CompanyId { get; set; }
        public string ItemId { get; set; }
        public string UnitMeasure { get; set; }
    }
}
