//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DashBoard_Availble_Stock
    {
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public string ItemId { get; set; }
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Item_Name { get; set; }
        public Nullable<double> Height { get; set; }
        public string UnitMeasure { get; set; }
        public Nullable<double> Stock { get; set; }
        public string WarehouseName { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
