//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_InvWarehouseBatch
    {
        public long TransectionId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string ItemId { get; set; }
        public string BatchCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public double Price { get; set; }
        public double Debit { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Brand { get; set; }
        public string ItemName { get; set; }
        public string UnitMeasure { get; set; }
        public double Credit { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
