//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_NewItemConsumption
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime MaterialIssuanceDate { get; set; }
        public string MirId { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public string ItemId { get; set; }
        public decimal IssuedQuantity { get; set; }
    }
}
