//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BusinessUnitCustomerRecievable
    {
        public string AccountCode { get; set; }
        public int CustomerId { get; set; }
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public double OpeningBalance { get; set; }
        public string ChartAccount { get; set; }
        public string Name { get; set; }
        public Nullable<double> Discount { get; set; }
        public bool Status { get; set; }
    }
}
