//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DashboardTransferItem
    {
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Brand { get; set; }
        public string Item_Name { get; set; }
        public string ItemId { get; set; }
        public int BusinessUnitId { get; set; }
        public string Name { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime DateTransfer { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public string IssuedTo { get; set; }
        public double Balance { get; set; }
        public int WarehouseId { get; set; }
        public string BatchCode { get; set; }
        public string Status { get; set; }
    }
}
