//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ItemHistoryDashboard
    {
        public Nullable<double> Price { get; set; }
        public double RecievedQuantity { get; set; }
        public string GrnId { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Brand { get; set; }
        public string ItemName { get; set; }
        public string ItemId { get; set; }
        public string VenderName { get; set; }
        public System.DateTime GoodRecieveDate { get; set; }
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
    }
}
