//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RecipeDetailWithItemName
    {
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Brand { get; set; }
        public string ItemName { get; set; }
        public double ItemPrice { get; set; }
        public string AccountCode { get; set; }
        public int CompanyId { get; set; }
        public string UnitMeasure { get; set; }
        public string RecipeId { get; set; }
        public decimal Quantity { get; set; }
        public int Expr1 { get; set; }
        public int WarehoueId { get; set; }
        public string ItemId { get; set; }
        public string PhaseId { get; set; }
        public string ProcedureId { get; set; }
        public int BusinessUnitId { get; set; }
        public string SalesItemId { get; set; }
    }
}
