//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetCurrentInfo_AllEmployees
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string MobileNo { get; set; }
        public string EMail { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public int EmployeeUid { get; set; }
        public string EmployeeTypeName { get; set; }
    }
}
