//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_invItemforpdnApprovel
    {
        public string ItemId { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Brand { get; set; }
        public string UnitMeasure { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> ItemWidth { get; set; }
        public int CompanyId { get; set; }
        public string PdnId { get; set; }
        public int BusinessUnitId { get; set; }
        public decimal Quantity { get; set; }
        public decimal ApprovedQuantity { get; set; }
        public System.DateTime ProjectionDate { get; set; }
        public string Status { get; set; }
    }
}
