//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_inv_warehouseItemBalance
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int WarehouseId { get; set; }
        public string BinCartId { get; set; }
        public string ItemId { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Balance { get; set; }
        public string WarehouseName { get; set; }
        public string BinCartName { get; set; }
    }
}
