//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ModuleFormInfo_ByRole
    {
        public System.Guid Login { get; set; }
        public Nullable<int> RoleId { get; set; }
        public int moduleFormId { get; set; }
        public Nullable<bool> active { get; set; }
        public string ModuleName { get; set; }
        public string ModuleCatName { get; set; }
        public string formName { get; set; }
    }
}
