//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CustomerInvoiceDetails
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string JobOrderId { get; set; }
        public string CustomerId { get; set; }
        public string AccountCode { get; set; }
        public string AccountTitle { get; set; }
        public double Dr_Amount { get; set; }
        public double Cr_Amount { get; set; }
        public string Naration { get; set; }
        public string VocherId { get; set; }
    }
}
