//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderDeliveryDetailforEdit
    {
        public int ItemDeliveryNo { get; set; }
        public string DeliveryId { get; set; }
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string ItemId { get; set; }
        public double DeliveredQuantity { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public double Price { get; set; }
        public double Quantity { get; set; }
        public double Discount { get; set; }
        public double CompanyDiscount { get; set; }
        public double NetAmount { get; set; }
        public Nullable<double> AprovedQuantity { get; set; }
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Brand { get; set; }
        public string Item_Name { get; set; }
    }
}
