//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SubCategoryColor_Size
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int id { get; set; }
        public string Sub_Category { get; set; }
        public int SizeId { get; set; }
        public string SizeName { get; set; }
        public string ColorName { get; set; }
    }
}
