//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ReportVoucher
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int TransectionId { get; set; }
        public string VocherId { get; set; }
        public string VoucherType { get; set; }
        public System.DateTime VocherDate { get; set; }
        public string Remarks { get; set; }
        public bool Posted { get; set; }
        public string PostedFrom { get; set; }
        public string PostedFromType { get; set; }
        public string FYear { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int AccountVocherChildCompanyId { get; set; }
        public int AccountVocherChildBusinessUnitId { get; set; }
        public int AccountVocherChildTransectionId { get; set; }
        public string AccountVocherChildVocherId { get; set; }
        public string AccountVocherChildVoucherType { get; set; }
        public int SrNo { get; set; }
        public string AccountCode { get; set; }
        public string AccountTitle { get; set; }
        public double Dr_Amount { get; set; }
        public double Cr_Amount { get; set; }
        public string Naration { get; set; }
        public double OpeningBalance { get; set; }
        public double ClossingBalance { get; set; }
        public string AccountVocherChildLastModifiedBy { get; set; }
        public System.DateTime AccountVocherChildCreatedOn { get; set; }
        public string AccountVocherChildCreatedBy { get; set; }
        public System.DateTime AccountVocherChildLastModifiedDate { get; set; }
    }
}
