//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DepartmentWiseRecipeSalesItem
    {
        public string SalesCategory { get; set; }
        public string Sub_Category { get; set; }
        public string SalesBrand { get; set; }
        public string Item_Name { get; set; }
        public int InquiryId { get; set; }
        public int CustomerId { get; set; }
        public int RecipeId { get; set; }
        public int CompanyId { get; set; }
        public string SalesItemId { get; set; }
        public int BusinessUnitId { get; set; }
    }
}
