//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetItemCompleteInfoWithoutStock
    {
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Brand { get; set; }
        public string Item_Name { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public double Weight { get; set; }
        public Nullable<double> Density { get; set; }
        public string RatioMeasure { get; set; }
        public string UnitMeasure { get; set; }
        public double Price { get; set; }
        public string AccountCode { get; set; }
        public Nullable<double> MaxStockLevel { get; set; }
        public Nullable<double> MinStockLevel { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ItemId { get; set; }
        public int CompanyId { get; set; }
        public string Color { get; set; }
        public double CDis { get; set; }
        public double SDis { get; set; }
        public double BDis { get; set; }
        public double IDis { get; set; }
        public string ArticleNo { get; set; }
        public string ForCustom { get; set; }
        public string SRO_Desc { get; set; }
        public string CustomDuty { get; set; }
        public string TDSNo { get; set; }
        public string HScode { get; set; }
        public string SROcode { get; set; }
        public string Packing { get; set; }
    }
}
