//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Report_DeliveryChallan
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string OrderType { get; set; }
        public string OrderId { get; set; }
        public string DeliveryId { get; set; }
        public int ItemDeliveryNo { get; set; }
        public string ItemId { get; set; }
        public double DeliveredQuantity { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Item_Name { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public double Weight { get; set; }
        public Nullable<double> Density { get; set; }
        public string RatioMeasure { get; set; }
        public string UnitMeasure { get; set; }
        public double Price { get; set; }
        public string AccountCode { get; set; }
        public Nullable<double> MaxStockLevel { get; set; }
        public Nullable<double> MinStockLevel { get; set; }
        public string OrderDelivery_VehicleNo { get; set; }
        public string OrderDelivery_DriverName { get; set; }
        public System.DateTime OrderDelivery_SalesDate { get; set; }
        public System.DateTime OrderDelivery_CreatedOn { get; set; }
        public string OrderDelivery_CreatedBy { get; set; }
        public string OrderDelivery_DriverMobileNo { get; set; }
        public string Region { get; set; }
        public string Zone { get; set; }
        public string CustomerName { get; set; }
        public string Brand { get; set; }
    }
}
