//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCustomerCareFeedBack
    {
        public string CustomerName { get; set; }
        public string OrderId { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public System.DateTime Date { get; set; }
        public string ComplaintName { get; set; }
        public string ContactNo { get; set; }
        public string ComplainDetail { get; set; }
        public string CustomerCareId { get; set; }
        public double ReturnQuantity { get; set; }
        public string ItemName { get; set; }
        public double DeliveredQuantity { get; set; }
        public int CustomerId { get; set; }
        public string DeliveryId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
    }
}
