//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_warehouseProductionDashboard
    {
        public string VenderName { get; set; }
        public double Debit { get; set; }
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string ItemId { get; set; }
        public string BatchCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Item_Name { get; set; }
        public double Price { get; set; }
        public double Balance { get; set; }
    }
}
