//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Report_OrderTypeWiseSalesDetail
    {
        public double DeliveredQuantity { get; set; }
        public double Price { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public string SaleInvoiceId { get; set; }
        public string Name { get; set; }
        public string ItemId { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string ItemName { get; set; }
        public System.DateTime SaleInvoiceDate { get; set; }
        public string UnitMeasure { get; set; }
    }
}
