//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BatchWithCompeletItemName
    {
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Brand { get; set; }
        public string Item_Name { get; set; }
        public string UnitMeasure { get; set; }
        public int CompanyId { get; set; }
        public string BatchId { get; set; }
        public decimal Quantity { get; set; }
        public string ItemId { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
    }
}
