//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOrderDelivery
    {
        public int BusinessUnitId { get; set; }
        public string OrderType { get; set; }
        public string OrderId { get; set; }
        public string DeliveryId { get; set; }
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime SalesDate { get; set; }
        public string ManualBillNo { get; set; }
    }
}
