//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LedgerBalanceDashboardFinancial
    {
        public string ChartAccount { get; set; }
        public string Title { get; set; }
        public double OpeningBalance { get; set; }
        public Nullable<int> HeadIndex { get; set; }
    }
}
