//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_StepStatusWithName
    {
        public int CompanyId { get; set; }
        public string ItemId { get; set; }
        public string StepId { get; set; }
        public string ProcedureId { get; set; }
        public string ProcedureName { get; set; }
        public string ProcedureTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public string BatchId { get; set; }
    }
}
