//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RecievedProductionDepartment
    {
        public string DepartmentName { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string PerformaInvoiceId { get; set; }
        public int DepartmentId { get; set; }
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Brand { get; set; }
        public string Item_Name { get; set; }
        public string UnitMeasure { get; set; }
        public int RecievedQty { get; set; }
        public int RemainingQty { get; set; }
        public int Color { get; set; }
        public int Size { get; set; }
        public string ItemId { get; set; }
        public int ForwardToDepartment { get; set; }
        public int ProductionId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    }
}
