//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetCurrentInfo_AllEmployees_Reports
    {
        public string EmployeeTypeName { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public int EmployeeUid { get; set; }
        public Nullable<double> SpecialAllowance { get; set; }
        public Nullable<double> PetrolAllowance { get; set; }
        public Nullable<double> MobileAllowance { get; set; }
        public Nullable<double> FoodAllowance { get; set; }
        public Nullable<double> IncomeText { get; set; }
        public Nullable<double> LoneDeduction { get; set; }
        public int CompanyId { get; set; }
        public string EmployeeId { get; set; }
        public int BusinessUnitId { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public byte[] Image { get; set; }
        public string MobileNo { get; set; }
        public string EMail { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Qualification { get; set; }
        public Nullable<double> Salary { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool LeavesAllowed { get; set; }
        public bool SundayOffAllowed { get; set; }
        public bool OverTimeAllowed { get; set; }
        public int EmployeeTypeEmployeeTypeId { get; set; }
        public string MyEmployeeHistoryEmployeeId { get; set; }
        public int EmployeeTypeId { get; set; }
        public string JobExperience { get; set; }
        public string Name { get; set; }
        public string MaritalStatus { get; set; }
    }
}
