//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ItemPriceDetail
    {
        public string Name { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public double Weight { get; set; }
        public Nullable<double> Density { get; set; }
        public double Price { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ItemId { get; set; }
    }
}
