//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PurchaseReturnWithItemName
    {
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public decimal ReturnedQuantity { get; set; }
        public string PurchaseReturnId { get; set; }
        public int BusinessUnitId { get; set; }
        public int CompanyId { get; set; }
        public string GatePasId { get; set; }
        public Nullable<decimal> RecievedQuantity { get; set; }
    }
}
