//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ForIncomeStatment
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public string AccountCode { get; set; }
        public string AccountTitle { get; set; }
        public Nullable<double> dr { get; set; }
        public Nullable<double> cr { get; set; }
        public string FH { get; set; }
        public string SH { get; set; }
        public string TH { get; set; }
    }
}
