//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int CompanyId { get; set; }
        public long TransectionId { get; set; }
        public string SerialNo { get; set; }
        public int BusinessUnitId { get; set; }
        public int WarehouseId { get; set; }
        public string ItemId { get; set; }
        public int ColorId { get; set; }
        public int SizeId { get; set; }
        public string BatchCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public double Price { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public double Balance { get; set; }
        public string IssuedTo { get; set; }
        public string RecordReference { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> LogId { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Item Item { get; set; }
    }
}
