//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENXAPI.Repisitory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int RegionId { get; set; }
        public int ZoneId { get; set; }
        public string ZoneName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Region Region { get; set; }
    }
}
